In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.cluster import KMeans
from imblearn.over_sampling import SMOTE 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from collections import Counter
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from imblearn.over_sampling import BorderlineSMOTE
from sklearn.neural_network import MLPClassifier
from matplotlib import pyplot
%matplotlib inline


In [3]:
df= pd.read_csv("Downloads/creditcard.csv")
df.drop(['Time'],axis=1,inplace=True)
print(df.shape)
df.head()
 


(284807, 30)


V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024 -0.054952  ... -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  0.753074  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 30 columns]

In [3]:
df.isnull().sum()
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(999, inplace=True)
print(type(df))
X = df
X = X.values
y = df['Class'].values
print(y)
print(X.shape)

<class 'pandas.core.frame.DataFrame'>
[0 0 0 ... 0 0 0]
(284807, 30)


In [4]:
sm = SMOTE(sampling_strategy=1,k_neighbors=2,random_state = 100) 
X_train_res, y_train_res = sm.fit_resample(X, y.ravel()) 
 
  
print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0))) 

After OverSampling, the shape of train_X: (568630, 30)
After OverSampling, the shape of train_y: (568630,) 

After OverSampling, counts of label '1': 284315
After OverSampling, counts of label '0': 284315


In [5]:
index=X.shape[0]/4;
start=3*index
data0=[]
print(index)
start=int(start)
for i in range(start,len(X)):
        #print(X[i])
        #print(i)
        data0.append(X[i])
        
print(data0)
df=pd.DataFrame(data0)
print(df.shape)

71201.75


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



(71202, 30)


In [6]:
    x=df.values  
    y = df[29]
print(y)

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ... 
71197    0.0
71198    0.0
71199    0.0
71200    0.0
71201    0.0
Name: 29, Length: 71202, dtype: float64


In [7]:
sm = SMOTE(sampling_strategy=1,k_neighbors=2,random_state = 100) 
X_train_res, y_train_res = sm.fit_resample(x, y.ravel()) 
data0=X_train_res
#print(X_train_res)
print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0))) 

After OverSampling, the shape of train_X: (142216, 30)
After OverSampling, the shape of train_y: (142216,) 

After OverSampling, counts of label '1': 71108
After OverSampling, counts of label '0': 71108


In [8]:
start1=2*index
start1=int(start1)
data1=[]
for i in range(start1,start):
        #print(X[i])
        data1.append(X[i])
        
print(data1)
df=pd.DataFrame(data1)
print(df.shape)
df0=pd.DataFrame(data0)
df1=pd.DataFrame(data1)
print(df0.shape)
print(df1.shape)
#print(data0.type)
#print(data0.shape)
#print(data1.shape)
#print(data2.shape)
#print(data3.shape)
# print(data2.shape)
# print(data3.shape)
final_data = np.concatenate((data0,data1), axis=0)
df=pd.DataFrame(final_data)
print(df.shape)
x=df.values  
y = df[29]
print(y)
# final_data=data0+data1+data2+data3
# df=pd.DataFrame(final_data)
# print(df.shape)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



(71202, 30)
(142216, 30)
(71202, 30)
(213418, 30)
0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
213413    0.0
213414    0.0
213415    0.0
213416    0.0
213417    0.0
Name: 29, Length: 213418, dtype: float64


In [9]:
sm = SMOTE(sampling_strategy=1,k_neighbors=2,random_state = 100) 
X_train_res, y_train_res = sm.fit_resample(x, y.ravel()) 
#data3=X_train_res
#print(X_train_res)
print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0))) 

After OverSampling, the shape of train_X: (284362, 30)
After OverSampling, the shape of train_y: (284362,) 

After OverSampling, counts of label '1': 142181
After OverSampling, counts of label '0': 142181


In [10]:
data1=X_train_res
print(data1.shape)
start2=index
start2=int(start2)
data2=[]
for i in range(start2,start1):
        #print(X[i])
        data2.append(X[i])
        
print(data2)
df=pd.DataFrame(data2)
print(df.shape)
df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
print(df1.shape)
print(df2.shape)
#print(data0.type)
#print(data0.shape)
#print(data1.shape)
#print(data2.shape)
#print(data3.shape)
# print(data2.shape)
# print(data3.shape)
final_data = np.concatenate((data1,data2), axis=0)
df=pd.DataFrame(final_data)
print(df.shape)
x=df.values  
y = df[29]
print(y)
# final_data=data0+data1+data2+data3
# df=pd.DataFrame(final_data)
# print(df.shape)

(284362, 30)


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



(71202, 30)
(284362, 30)
(71202, 30)
(355564, 30)
0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
355559    0.0
355560    0.0
355561    0.0
355562    0.0
355563    0.0
Name: 29, Length: 355564, dtype: float64


In [11]:
sm = SMOTE(sampling_strategy=1,k_neighbors=2,random_state = 100) 
X_train_res, y_train_res = sm.fit_resample(x, y.ravel()) 
#data3=X_train_res
#print(X_train_res)
print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0))) 

After OverSampling, the shape of train_X: (426582, 30)
After OverSampling, the shape of train_y: (426582,) 

After OverSampling, counts of label '1': 213291
After OverSampling, counts of label '0': 213291


In [12]:
data2=X_train_res
print(data2.shape)
start3=0
#start2=int(start2)
data3=[]
for i in range(start3,start2):
        #print(X[i])
        data3.append(X[i])
        
print(data3)
df=pd.DataFrame(data3)
print(df.shape)
df1=pd.DataFrame(data2)
df2=pd.DataFrame(data3)
print(df1.shape)
print(df2.shape)
#print(data0.type)
#print(data0.shape)
#print(data1.shape)
#print(data2.shape)
#print(data3.shape)
# print(data2.shape)
# print(data3.shape)
final_data = np.concatenate((data2,data3), axis=0)
df=pd.DataFrame(final_data)
print(df.shape)
x=df.values  
y = df[29]
print(y)
# final_data=data0+data1+data2+data3
# df=pd.DataFrame(final_data)
# print(df.shape)

(426582, 30)


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



(71201, 30)
(426582, 30)
(71201, 30)
(497783, 30)
0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
         ... 
497778    0.0
497779    0.0
497780    0.0
497781    0.0
497782    0.0
Name: 29, Length: 497783, dtype: float64


In [13]:
sm = SMOTE(sampling_strategy=1,k_neighbors=2,random_state = 100) 
X_train_res, y_train_res = sm.fit_resample(x, y.ravel())
#oversample = BorderlineSMOTE()
#X_train_res, y_train_res = oversample.fit_resample(x, y)
# summarize the new class distribution
#counter = Counter(y)
#print(counter)
#data3=X_train_res
#print(X_train_res)
print('After OverSampling, the shape of train_X: {}'.format(X_train_res.shape)) 
print('After OverSampling, the shape of train_y: {} \n'.format(y_train_res.shape)) 
  
print("After OverSampling, counts of label '1': {}".format(sum(y_train_res == 1))) 
print("After OverSampling, counts of label '0': {}".format(sum(y_train_res == 0))) 

After OverSampling, the shape of train_X: (568630, 30)
After OverSampling, the shape of train_y: (568630,) 

After OverSampling, counts of label '1': 284315
After OverSampling, counts of label '0': 284315


In [14]:
print(X_train_res.shape)
print(y_train_res.shape)

x_train,x_test,y_train,y_test = train_test_split(X_train_res,y_train_res,random_state=100,test_size=0.1,stratify=y_train_res)
print("Before OverSampling, counts of label '1': {}".format(sum(y_train == 1))) 
print("Before OverSampling, counts of label '0': {} \n".format(sum(y_train == 0))) 

(568630, 30)
(568630,)
Before OverSampling, counts of label '1': 255884
Before OverSampling, counts of label '0': 255883 



In [15]:
def accuracy(confusion_matrix):
   diagonal_sum = confusion_matrix.trace()
   sum_of_all_elements = confusion_matrix.sum()
   return diagonal_sum / sum_of_all_elements

In [16]:
classifier = MLPClassifier(hidden_layer_sizes=(150,100,50), max_iter=300,activation = 'relu',solver='adam',random_state=1)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_pred, y_test)
print("Confusion Matrix:\n",cm)
print("Accuracy of MLPClassifier : ", accuracy(cm))

Confusion Matrix:
 [[28432     0]
 [    0 28431]]
Accuracy of MLPClassifier :  1.0


In [17]:
knn= KNeighborsClassifier(n_neighbors = 5)
knn.fit(x_train, y_train)
y_pred_5 = knn.predict(x_test)
print("Accuracy with k=5", accuracy_score(y_test, y_pred_5)*100)
print("Confusion Matrix:\n",confusion_matrix(y_pred_5,y_test))

Accuracy with k=5 99.95955190545698
Confusion Matrix:
 [[28418     9]
 [   14 28422]]


In [18]:
model = LogisticRegression()
model.fit(X_train_res,y_train_res)
pred = model.predict(x_test)
print('Accuracy ',accuracy_score(y_test,pred))
print(classification_report(y_test,pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,pred))

/home/vinay/.local/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Accuracy  0.999718621951005
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     28432
         1.0       1.00      1.00      1.00     28431

    accuracy                           1.00     56863
   macro avg       1.00      1.00      1.00     56863
weighted avg       1.00      1.00      1.00     56863

Confusion Matrix:
 [[28421    11]
 [    5 28426]]


In [19]:
print

<function print>

In [ ]:
svc_model  = SVC(kernel='rbf')
svc_model.fit(x_train, y_train)
 
prediction = svc_model.predict(x_test)
 
print(svc_model.score(x_train, y_train))
print(svc_model.score(x_test, y_test))
print("Confusion Matrix:\n",confusion_matrix(prediction,y_test))

In [ ]:
model = keras.Sequential([
    layers.Dense(4, activation='relu', input_shape=[33]),
    layers.Dense(4, activation='relu'),    
    layers.Dense(1, activation='sigmoid'),
])